# docker-compose.yml
services:
  app:
    image: YoussefZeroual/ppi-analyser:latest
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: unless-stopped
